### ISSUE TITLE
Error: Cannot use a scalar value as an array

### ISSUE THREAD

**Issue by vaniwiki** [ComboStrap/combo#94] opened 2024-04-09 02:28 UTC
Recently I have been getting this message in a few namespaces where I have sidebars. These sidebars contain only text, and are just to keep the main sidebar and page explorer from showing. Deleting the sidebar cleared up this message.

```
Error: Cannot use a scalar value as an array

An unforeseen error has occured. This is most likely a bug somewhere. It might be a problem in the combo plugin.

More info has been written to the DokuWiki error log.
```

Should I take a look at the error log to find out more?

**Comment by gerardnico** [comment] 2024-04-09 05:55
Oh men sorry for that. If you give me the sidebar content, I can test it in the demo website.

The log is always good because it will give the location of the error.

**Comment by vaniwiki** [comment] 2024-04-09 07:18
Well, it wasnt like this until the last update. So I figured something had happened... Nothing is in those sidebars, just some text to override the root sidebar, to not show page eplorer. It happens on several pages. Maybe not even related to sidebar, but that seems to fix it.

**Comment by gerardnico** [comment] 2024-04-09 07:37
Works on the [demo](https://demo.combostrap.com/sidetest/start)

**Comment by gerardnico** [comment] 2024-04-09 07:38
Do you have the log?

**Comment by vaniwiki** [comment] 2024-04-09 07:56
Exactly which log is that? I'm looking at cache/debug.log now...

**Comment by vaniwiki** [comment] 2024-04-09 07:59
Sorry, just found it:

```
2024-04-09 01:50:01	/home/vaniw/public_html/lib/plugins/sqlite/SQLiteDB.php(493)	SQLite: Could not read dbversion from opt table due to unexpected error
  {
      "dbname": "combo-secondary",
      "exception": "PDOException",
      "message": "SQLSTATE[HY000]: General error: 14 unable to open database file",
      "code": 0
  }
2024-04-09 01:49:58	/home/vaniw/public_html/lib/plugins/combo/ComboStrap/Call.php(948)	Error: Cannot use a scalar value as an array
  #0 /home/vaniw/public_html/lib/plugins/combo/ComboStrap/Outline.php(298): ComboStrap\Call->setAttribute()
  #1 /home/vaniw/public_html/lib/plugins/combo/ComboStrap/Outline.php(110): ComboStrap\Outline->buildOutline()
  #2 /home/vaniw/public_html/lib/plugins/combo/ComboStrap/Outline.php(123): ComboStrap\Outline->__construct()
  #3 /home/vaniw/public_html/lib/plugins/combo/action/instructionspostprocessing.php(147): ComboStrap\Outline::createFromCallStack()
  #4 /home/vaniw/public_html/inc/Extension/EventHandler.php(80): action_plugin_combo_instructionspostprocessing->_post_processing()
  #5 /home/vaniw/public_html/inc/Extension/Event.php(97): dokuwiki\Extension\EventHandler->process_event()
  #6 /home/vaniw/public_html/inc/Extension/Event.php(137): dokuwiki\Extension\Event->advise_after()
  #7 /home/vaniw/public_html/inc/Extension/Event.php(200): dokuwiki\Extension\Event->trigger()
  #8 /home/vaniw/public_html/inc/parser/handler.php(147): dokuwiki\Extension\Event::createAndTrigger()
  #9 /home/vaniw/public_html/inc/Parsing/Parser.php(127): Doku_Handler->finalize()
  #10 /home/vaniw/public_html/inc/parserutils.php(234): dokuwiki\Parsing\Parser->parse()
  #11 /home/vaniw/public_html/inc/parserutils.php(198): p_get_instructions()
  #12 /home/vaniw/public_html/inc/parserutils.php(520): p_cached_instructions()
  #13 /home/vaniw/public_html/inc/parserutils.php(299): p_render_metadata()
  #14 /home/vaniw/public_html/inc/common.php(262): p_get_metadata()
  #15 /home/vaniw/public_html/doku.php(101): pageinfo()
  #16 {main}
2024-04-09 01:50:00	/home/vaniw/public_html/lib/plugins/extlist/syntax.php(185)	E_WARNING: Undefined array key "ol"
  #0 /home/vaniw/public_html/lib/plugins/extlist/syntax.php(185): dokuwiki\ErrorHandler::errorHandler()
  #1 /home/vaniw/public_html/lib/plugins/extlist/syntax.php(279): syntax_plugin_extlist->olist_marker()
  #2 /home/vaniw/public_html/lib/plugins/extlist/syntax.php(498): syntax_plugin_extlist->_openItem()
  #3 /home/vaniw/public_html/inc/parser/handler.php(298): syntax_plugin_extlist->handle()
  #4 /home/vaniw/public_html/inc/Parsing/Lexer/Lexer.php(269): Doku_Handler->plugin()
  #5 /home/vaniw/public_html/inc/Parsing/Lexer/Lexer.php(205): dokuwiki\Parsing\Lexer\Lexer->invokeHandler()
  #6 /home/vaniw/public_html/inc/Parsing/Lexer/Lexer.php(146): dokuwiki\Parsing\Lexer\Lexer->dispatchTokens()
  #7 /home/vaniw/public_html/inc/Parsing/Parser.php(113): dokuwiki\Parsing\Lexer\Lexer->parse()
  #8 /home/vaniw/public_html/inc/parserutils.php(234): dokuwiki\Parsing\Parser->parse()
  #9 /home/vaniw/public_html/inc/parserutils.php(198): p_get_instructions()
  #10 /home/vaniw/public_html/inc/parserutils.php(520): p_cached_instructions()
  #11 /home/vaniw/public_html/inc/parserutils.php(299): p_render_metadata()
  #12 /home/vaniw/public_html/inc/common.php(262): p_get_metadata()
  #13 /home/vaniw/public_html/doku.php(101): pageinfo()
  #14 {main}

```

and it continues with more errors for another 30MB... How much do you need?

**Comment by vaniwiki** [comment] 2024-04-09 08:13
Quite possibly I have plugins that mess things up as well, I see extended list syntax is throwing errors. And others, I'm sure. Sent you the log per email, hoping that works. In case you need to look closer...

**Comment by vaniwiki** [comment] 2024-04-11 06:07
I'm starting to wonder if this issue is related to the pagequery plugin. I didn't notice any isses with this plugin at first, but now that I'm looking, it seems that the pages and sections crash are pagequery pages, and might not be related to the sidebar. It was working fine until recently, maybe the last couple of commits. Just trying to understand what I'm doing wrong...

**Comment by vaniwiki** [comment] 2024-04-11 06:11
When I edited the pages in my editor and replaced the pagequery code, it still crashed. But then I deleted the file and made a new one with plain text, and it works again. Will repeat for all pages and update if that solves the issue.

**Comment by gerardnico** [comment] 2024-04-11 07:19
I have adjusted the code to ignore the setting. For whatever reason, the code thinks that this is a header.
It may be related to the disable heading. I can't reproduce it, and then I made a defensive adjustment.

**Comment by vaniwiki** [comment] 2024-04-12 02:37
Now I'm getting this:

```
Error: Named parameter $level overwrites previous argument

An unforeseen error has occured. This is most likely a bug somewhere. It might be a problem in the combo plugin.

More info has been written to the DokuWiki error log.
```

**Comment by vaniwiki** [comment] 2024-04-12 02:45
From the error log:

```
2024-04-12 00:01:35	/home/vaniw/public_html/inc/parserutils.php(535)	Error: Named parameter $level overwrites previous argument
  #0 /home/vaniw/public_html/inc/parserutils.php(299): p_render_metadata()
  #1 /home/vaniw/public_html/inc/common.php(262): p_get_metadata()
  #2 /home/vaniw/public_html/doku.php(101): pageinfo()
  #3 {main}
2024-04-12 00:01:55	/home/vaniw/public_html/inc/parserutils.php(535)	Error: Named parameter $level overwrites previous argument
  #0 /home/vaniw/public_html/inc/parserutils.php(299): p_render_metadata()
  #1 /home/vaniw/public_html/inc/Cache/CacheRenderer.php(79): p_get_metadata()
  #2 /home/vaniw/public_html/inc/Cache/Cache.php(79): dokuwiki\Cache\CacheRenderer->addDependencies()
  #3 /home/vaniw/public_html/lib/plugins/combo/ComboStrap/FetcherMarkup.php(419): dokuwiki\Cache\Cache->useCache()
  #4 /home/vaniw/public_html/lib/plugins/combo/ComboStrap/FetcherMarkup.php(987): ComboStrap\FetcherMarkup->shouldProcess()
  #5 /home/vaniw/public_html/lib/plugins/combo/ComboStrap/FetcherMarkup.php(770): ComboStrap\FetcherMarkup->processIfNeeded()
  #6 /home/vaniw/public_html/lib/plugins/combo/ComboStrap/TemplateForWebPage.php(618): ComboStrap\FetcherMarkup->getFetchString()
  #7 /home/vaniw/public_html/lib/plugins/combo/ComboStrap/TemplateForWebPage.php(162): ComboStrap\TemplateForWebPage->getModel()
  #8 /home/vaniw/public_html/lib/plugins/combo/ComboStrap/FetcherPage.php(154): ComboStrap\TemplateForWebPage->render()
  #9 /home/vaniw/public_html/lib/plugins/combo/action/docustom.php(180): ComboStrap\FetcherPage->getFetchString()
  #10 /home/vaniw/public_html/inc/Extension/EventHandler.php(80): action_plugin_combo_docustom->executeComboDoAction()
  #11 /home/vaniw/public_html/inc/Extension/Event.php(75): dokuwiki\Extension\EventHandler->process_event()
  #12 /home/vaniw/public_html/inc/ActionRouter.php(83): dokuwiki\Extension\Event->advise_before()
  #13 /home/vaniw/public_html/inc/ActionRouter.php(49): dokuwiki\ActionRouter->setupAction()
  #14 /home/vaniw/public_html/inc/ActionRouter.php(62): dokuwiki\ActionRouter->__construct()
  #15 /home/vaniw/public_html/inc/actions.php(19): dokuwiki\ActionRouter::getInstance()
  #16 /home/vaniw/public_html/doku.php(131): act_dispatch()
  #17 {main}
2024-04-12 00:02:20	/home/vaniw/public_html/lib/plugins/combo/ComboStrap/Tag/AdTag.php(1)	E_ERROR: Allowed memory size of 134217728 bytes exhausted (tried to allocate 32768 bytes)
  #0 [internal function]: dokuwiki\ErrorHandler::fatalShutdown()
  #1 {main}
```

**Comment by gerardnico** [comment] 2024-04-12 05:51
Can I get the markup that create this error. A reproducer? If I can't reproduce it. It's pretty difficult for me to apply the good patch.

**Comment by vaniwiki** [comment] 2024-04-12 06:57
This is the current issue, showing sidebar that only has some text content, and a plain index page with a heading only... But it may be some metadata there as well. I have set the index page to display as hamburger, to not get this error. I thought it was directly related to this patch.

**Comment by gerardnico** [comment] 2024-04-12 07:04
This error happens in dokuwiki code. 

Therefore I can't change the code. I need a reproducer (markup wiki) to see which bad data we generate.

I made blind change tested with my tests. Now, I just can't do that anymore.

**Comment by gerardnico** [comment] 2024-04-14 07:26
I'm going to close it as I don't have any reproducer.

If you get a reproducer where I can work on, please post it.

Thanks for all.

**Closed by gerardnico** 2024-04-14 07:26 UTC
Labels: bug
