### ISSUE TITLE
Missing links become relative to current page

### ISSUE THREAD

**Issue by vaniwiki** [ComboStrap/combo#96] opened 2024-04-12 10:12 UTC
I have many missing (red) links in my content, however unfortunate that is. The good news was that I also have a redirect file where most of the red links are hard coded, redirecting to their proper page. The bad news is that in my current ComboStrap setup, these red links point to pages relative to themselves. Let's see if I can reproduce on [demo](https://demo.combostrap.com/redlink)...

**Comment by gerardnico** [comment] 2024-04-13 09:05
This is a duplicate of relative vs absolute link. No?

**Comment by vaniwiki** [comment] 2024-04-14 03:22
Yes, duplicate. What happened is, I thought I hadn't posted it, due to you having closed the issue. So I made a new issue.

I would argue that it is important to keep defalt DokuWiki behavior. You may argue it makes more sense to not, therefore it is alright to override it, but please don't force it. I have hundred thousand text files, with millions of links. I have ~2500 redirect entries, just to make broken links point to its proper place. I can't find all missing links without using dokuwiki plugins and go through one by one, and I would prefer not to add a colon in front of all my links in all my documents.

Different people have different setups, so hijacking headers and links may produce unwanted behaviour. I had functionality working for years that suddenly stopped working because ComboStrap is taking over. And if I turn off either headers or links, basic ComboStrap functionality breaks, like page explorer and other things...

I have other (minor) issues with links also, so maybe I should just try to turn off the ComboStrap links altogether and report issues here and hope to sort it out. I think combostrap has a <link> syntax that will give ComboStrap link enhancements if I need it...? (like adding icon to the link, etc.)

**Comment by vaniwiki** [comment] 2024-04-14 03:48
Yikes! Disabling the link component indeed messes up the page explorer, like I remembered. But interestingly, immediately all those red links became blue. It seems the redirect file makes those pages appear existent. Nice!

I like page explorer, but I also like having all my red non-existent links become blue, leading to its target. Like I said, I could potentially add the colon in front of absolutely all my links, but that feels kind of unnecessary, if you get me. I can also look for other navigational plugins, but another issue is that this turns off automatic tooltips, which I have come to depend on...

I think the "DokuWiki way" to make longer relative links is to add a fullstop in front `[[.:page:another page]]`.

**Comment by gerardnico** [comment] 2024-04-14 07:21
As I said your link should not be red, if your page exists.

If you create a link to a non-existant with a simple name, it will be relative to your namespace and not on the root.
As it does not make sense at all.

**Closed** 2024-04-14 07:22 UTC

**Comment by vaniwiki** [comment] 2024-04-14 09:13
The main issue is that ComboStrap handles links differently than DokuWiki.

In **DokuWiki** `[[page]]` is a relative link, `[[page:another]]` is an absolute one. I think `[[.:page]]` is hard coded relative and `[[:page:another]]` hard coded absolute.

In **ComboStrap** `[[page]]` is a relative link, `[[page:another]]` is also a relative link, unless it exists, then it's absolute... There seems to be some inconsistency, is all I'm pointing out.

My missing links (eg. `[[books:bg:16:2]]`) are absolute in DokuWiki, and works perfectly with redirect plugin (minus tooltip popups, but I can live with that). However, ComboStrap makes them relative, so they throw a redlink and 404.

Like I mention, both the headings and links functionality from ComboStrap causes issues with how I use DokuWiki, so I'd be better off with these setting off completely. But this also produces unwanted results with other components in ComboStrap. So it seems I have to choose between "this functionality" or "that functionality"...

In this instance, I could also run a replace on 100k files, and not complain. But there are other link issues I have, including brackets within links, and search, which earlier would highlight my serch terms on the page of the link. Somewhere along the line this functionality stopped working, and I guess I accepted it as trade-offs to gain new functionality.

But why not try to get all the functionality working? I'm not a programmer, but a simpleton that barely knows some html and css code. Programming to me is like French, I don't understand it. But to you, it's your first language. That's why I'm asking.

**Comment by gerardnico** [comment] 2024-04-14 09:22
Simple name has absolute is wrong you are right as it brings inconsistencies.

I introduced a patch to handle relative link as absolute when the file exists because a lot of plugin uses this syntax (move plugin does not add the root sign for instance when it rewrites the relative link

A writer does not want to add extra characters because it adds an extra effort that is not needed. 

I would also add that this is the standard everywhere.

Again, you should have no problem when the file exists.
